services:
  redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"
      volumes:
        - redis_data:/data
      restart: unless-stopped

  qdrant:
      image: qdrant/qdrant:latest
      container_name: qdrant
      ports:
        - "6333:6333"
        - "6334:6334"
      volumes:
        - qdrant_storage:/qdrant/storage
      restart: unless-stopped

  neo4j:
      image: neo4j:latest
      container_name: neo4j
      environment:
        - NEO4J_AUTH=neo4j/lightrag123  
      ports:
        - "7687:7687"  
        - "7474:7474"  
      volumes:
        - neo4j_data:/data
        - neo4j_logs:/logs
        - neo4j_import:/import
        - neo4j_plugins:/plugins
      restart: unless-stopped

  postgres:
      image: ankane/pgvector:latest
      container_name: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: lightrag
        POSTGRES_PASSWORD: lightrag123
        POSTGRES_DB: lightragdb
      volumes:
        - pg_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "5432:5432"


  lightrag:
    container_name: lightrag
    image: ghcr.io/hkuds/lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/hkuds/lightrag:latest
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - qdrant
      - neo4j
      - postgres
    dns:
      - 8.8.8.8
      - 1.1.1.1


volumes:
  redis_data:
  qdrant_storage:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  pg_data: